name: Android CI

on:
  push:
    branches:
      - Dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run UI Tests
        run: ./gradlew connectedAndroidTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/tests

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-results
          path: app/build/outputs/androidTest-results/connected
